### ISSUE TITLE
Problems with debugging PP

### ISSUE THREAD

**Issue by flip111** [hoaproject/Compiler#18]
Hi i've a problem with some pp syntax, i think the wrong repetition is getting precendence but i don't understand why. See below for relevant info.

notation under test:
```
Ab ::= Cd
```

pp
```
%skip S [\x09\x0A\x0D\x20]
%token Production_a ::=
%token NameStartChar \w
%token Choice_a \|
%token SequenceOrDifference_a -
%token Item_a [\?\*\+]

#Production:
	NCName() ::Production_a:: Choice()

#NCName:
	::NameStartChar:: (::NameStartChar::)*

#Choice:
	SequenceOrDifference() (::Choice_a:: SequenceOrDifference())*

#SequenceOrDifference:
	(NCName() (::SequenceOrDifference_a:: NCName() | NCName()*))?
```

Trace:
```
 #  namespace     token name            token value                     offset
-------------------------------------------------------------------------------
 0  default       NameStartChar         A                                    0
 1  default       NameStartChar         b                                    1
 2  default       Production_a          ::=                                  3
 3  default       NameStartChar         C                                    7
 4  default       NameStartChar         d                                    8
 5  default       EOF                                                        9


>  enter Production (#Production)
>  >  enter NCName
         token NameStartChar, consumed A
>  >  >  enter 17
>  >  >  >  enter 16 (#NCName)
               token NameStartChar, consumed b
<  <  <  <  ekzit 16
<  <  <  ekzit 17
<  <  ekzit NCName
      token Production_a, consumed ::=
>  >  enter Choice
>  >  >  enter SequenceOrDifference
>  >  >  >  enter 12
>  >  >  >  >  enter NCName
                  token NameStartChar, consumed C
>  >  >  >  >  >  enter 17
<  <  <  <  <  <  ekzit 17
<  <  <  <  <  ekzit NCName
>  >  >  >  >  enter 11
>  >  >  >  >  >  enter 10 (#SequenceOrDifference)
>  >  >  >  >  >  >  enter 9
>  >  >  >  >  >  >  >  enter NCName
                           token NameStartChar, consumed d
>  >  >  >  >  >  >  >  >  enter 17
<  <  <  <  <  <  <  <  <  ekzit 17
<  <  <  <  <  <  <  <  ekzit NCName
<  <  <  <  <  <  <  ekzit 9
<  <  <  <  <  <  ekzit 10
<  <  <  <  <  ekzit 11
<  <  <  <  ekzit 12
<  <  <  ekzit SequenceOrDifference
>  >  >  enter 5
<  <  <  ekzit 5
<  <  ekzit Choice
<  ekzit Production


>  #Production
>  >  #NCName
>  >  #Choice
>  >  >  #SequenceOrDifference
>  >  >  >  #NCName
>  >  >  >  #NCName
```

At:
```
				  token NameStartChar, consumed C
>  >  >  >  >  >  enter 17
```
Expect:
```
>  >  >  >  >  >  >  enter 16 (#NCName)
```
But get:
```
`<  <  <  <  <  <  ekzit 17`
```

I think there is a preference for the second `NCName()` here:
```
#SequenceOrDifference:
	(NCName() (::SequenceOrDifference_a:: NCName() |    >>> NCName()* <<<    ))?
```
Instead of trying to match another `::NameStartChar::` here:
```
#NCName:
	::NameStartChar:: ( >>> ::NameStartChar:: <<<)*
```
Please note that i put `>>>    <<<` just to indicate the flow of the grammar, refer to `case.pp` for the actual grammar.

**Comment by Hywan** [comment]
ping?

**Comment by flip111** [comment]
pong

**Comment by Hywan** [comment]
No more activity on this issue. Can we close or is it not resolved yet?

**Comment by flip111** [comment]
As you can see, you assigned @CircleCode but he did not reply. The open question _is this intended behavior by design?_ can not be answered on my own (because i'm not the designer of this library). So yes it's still open...

**Comment by Hywan** [comment]
@CircleCode is on the opposite side of the earth (based on its usual location) for a while. I take the lead on this issue and try to answer to the question as soon as possible.

**Comment by flip111** [comment]
Ok thank you :)

**Comment by flip111** [comment]
Ok after two years i think this issue is resolved. What happens is that even though the parser is DEPTH-FIRST and yes it should match more `(::NameStartChar::)*` in rule `NCName`. What i think happens is that it runs out of tokens this way (which is good) but then it goes a level higher and comes back to rule `SequenceOrDifference` and this rule is `(NCName() (::SequenceOrDifference_a:: NCName() | NCName()*))?` and now it consumed all the tokens when diving into the first `NCName()` so then it continues with `(::SequenceOrDifference_a:: NCName() | NCName()*)`

And here something very sneaky but logical occurs. Since it's looking for `( something here )` which in itself is NOT optional or `zero or more` it will have problems closing this rule, therefor it will backtrack on the path which was just taken to see if it can "free up any tokens", it frees up one `::NameStartChar::`. Now it can match this token in the second `NCName()` in `(::SequenceOrDifference_a:: NCName() | NCName()*)`. EVEN THOUGH this part has a `*` `zero or more` quantifier behind it (so this inner-part doesn't infact have to match).

So the confusion here (on my part) was to assume that the parser knows that it doesn't have to match the outer `( )` because one of the inner choices was entirely optional. In a nutshell `foo*` is not the same as `(foo*)`

**Comment by Hywan** [comment]
Good to hear!

**Comment by flip111** [comment]
This should be documented that `(foo*)` and `foo*` are not the same.
