### ISSUE TITLE
PP supports in editors

### ISSUE THREAD

**Issue by Hywan** [hoaproject/Compiler#42]
Hello :-),

Supported editors:
  * Emacs, https://github.com/stevenremot/hoa-pp-mode,
  * Vim, https://github.com/Hywan/Dotfiles/blob/master/vim/syntax/pp.vim.

Should we add these resources in this library or in [`Hoa\Devtools`](http://central.hoa-project.net/Resource/Library/Devtools) @hoaproject/hoackers?

**Comment by jubianchi** [comment]
> Should we add these resources in this library or in Hoa\Devtools

:+1: **in this library** is to me, a library for Hoa developers (or should I say contributors) not users. Those 2 resources are user-oriented.

**Comment by Hywan** [comment]
Agree. Waiting for the opinion of @CircleCode :-).

**Comment by vonglasow** [comment]
:+1: Agree with @jubianchi

**Comment by Hywan** [comment]
Any one for a PR?
