### ISSUE TITLE
Dependency to mbstring

### ISSUE THREAD

**Issue by lovenunu** [hoaproject/Compiler#50]
Hi, as the lexer uses [`mb_strlen`](https://github.com/hoaproject/Compiler/blob/master/Llk/Lexer.php#L133),  I think that the composer.json should require `ext-mbstring` or [`symfony/polyfill-mbstring`](https://github.com/symfony/polyfill-mbstring), don't you ? :)

**Comment by Hywan** [comment]
Hello :-),

`hoa/compiler` [requires `hoa/regex`](https://github.com/hoaproject/Compiler/blob/1496646bfa85f88ab50b651857fbf4bbd15dbca1/composer.json#L34) which [requires `hoa/ustring`](https://github.com/hoaproject/Regex/blob/a0e01a81fae0e7a325a5d958a269d611a5252690/composer.json#L28), which [already solve](https://github.com/hoaproject/Ustring/blob/9f76b9aae5901b4f476ef854e29ccd746d6899d2/Ustring.php#L1060-L1066) this issue. See https://github.com/hoaproject/Ustring/pull/5 for the reason of this approach.

**Comment by lovenunu** [comment]
Oops, sorry I didn't go deep enough :sweat_smile: Well now I know `hoa/ustring` :yum:

**Comment by Hywan** [comment]
;-)
