### ISSUE TITLE
Add $node->getOffset() support

### ISSUE THREAD

**Issue by SerafimArts** [hoaproject/Compiler#75]
In addition to synax analysis (lex), there is also a semantic analysis of code. And in the case of errors of semantics, it is required to understand exactly where the error occurred. Like:

```php
function a(int $b) {}
a(null);

// Error: Integer required in XXX file on line 2 and offset 3, but null given.
// a(null);
//    ^
```

The only way to get this information is the TreeNode instance:
```php
class TreeNode {
    +public function getOffset(): int;
}
```

I tried to implement this in the form of Pull Request, but the source code is pretty confusing =\

**Comment by SerafimArts** [comment]
Hmmm, same with #70 yep?

**Comment by Hywan** [comment]
Yes, duplicate of #70.
